version: '3'
services:
  authbackend:
    image: badconfig/tiny_auth
    container_name: authbackend
    tty: true
    ports:
      - "8088:8088"
    environment:
      - DATABASE_URL=postgres://main:NavwNgTnxyWsz7hy5yRmEKC4X@auth_postgres:5432/diesel_db
    networks:
      - app-network
  auth_postgres:
    image: "postgres:12.6"
    container_name: auth_postgres
    restart: unless-stopped
    ports:
      - "7088:5432"
    environment:
      POSTGRES_DB: diesel_db
      POSTGRES_PASSWORD: NavwNgTnxyWsz7hy5yRmEKC4X
      POSTGRES_USER: main
    networks:
      - app-network
    volumes:
      - pg_auth:/var/lib/postgresql/data
volumes:
  pg_auth:
networks:
  app-network:
    external: true

